name: Build

on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run build
      - run: rm .gitignore
      - run: git add build
      - run: git branch pages
      - run: git push pages
